First commit
martinssliede/Java-homeworks pull request #2
Opened 2023-05-11 05:40 UTC by martinssliede

2023-05-14 20:05 UTC, janistumpelis requested changes
Paldies, kopumā ir tīri ok, pāris sīkumi jāpielabo un jāuztaisa tas ASCII 👍

2023-05-14 20:05 UTC, janistumpelis commented on src/main/java/io/codelex/loops/practice/Exercise8_AsciiFigure.java
> +    // PIEDOD, ES NESAPROTU ŠĪ UZDEVUMA LOĢIKU. NEREDZU SAIKNI STARP IEVADĀMĀ LIELUMU, UN SIMBOLU IZKĀRTOJUMU. :(
Par šito ir tā - ievadītais skaitlis nosaka rindu skaitu, pieņemsim, ka ievada skaitli 5.
Pirmajā rindā būs 0 zvaigznītes; otrajā rindā būs 8 zvaigznītes; trešajā 16; ceturtajā 24 un piektajā 32. Tā tad katrā rindā par 8 vairāk, bet kopējais platums ir (n-1)*8, kas atbilst pēdējās rindā zvaigznīšu skaitam.

2023-05-15 09:46 UTC, martinssliede commented
Izdzēsu .idea, pievienoju labojumus. Sagaidu akceptu un varu mērdžot?

2023-05-16 06:02 UTC, janistumpelis approved these changes
Lieku approve, bet nu te tāpat palika tā .idea mape ar failiem. :D Tev būtu jāaizver Intellij, tā mape jāizdzēš un tad commit + push. Pēc tam vari mērdžot.

2023-05-16 06:37 UTC, martinssliede commented
Izdzēsu tā pat kā 1. MD gadījumā. Ja vēl joprojām ir, tad man noteikti būs nepieciešama palīdzība ar šo.

2023-05-16 06:39 UTC, merged